version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY='django-insecure-r1)*=a3dk7t6y7=d2%6tw$roi)n*9jxeg)#u%%n3s_!=io5(g&')
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerce

volumes:
  mongodb_data:
  static_volume: